INSERT INTO `sql_lianxi` (`姓名`, `email`, `job_title`) VALUES ('John Doe', 'john.doe@example.com', 'HR Manager');
INSERT INTO `sql_lianxi` (`姓名`, `email`, `job_title`) VALUES ('Jane Smith', 'jane.smith@example.com', 'Software Engineer');
INSERT INTO `sql_lianxi` (`姓名`, `email`, `job_title`) VALUES ('Mike Johnson', 'mike.johnson@example.com', 'Financial Analyst');
INSERT INTO `sql_lianxi` (`姓名`, `email`, `job_title`) VALUES ('Emily Brown', 'emily.brown@example.com', 'Marketing Specialist');
INSERT INTO `sql_lianxi` (`姓名`, `email`, `job_title`) VALUES ('David Wilson', 'david.wilson@example.com', 'Operations Manager');
INSERT INTO `sql_lianxi` (`姓名`, `email`, `job_title`) VALUES ('Sarah Lee', 'sarah.lee@example.com', 'IT Support');
INSERT INTO `sql_lianxi` (`姓名`, `email`, `job_title`) VALUES ('Chris Anderson', 'chris.anderson@example.com', 'Accountant');
INSERT INTO `sql_lianxi` (`姓名`, `email`, `job_title`) VALUES ('Lisa Taylor', 'lisa.taylor@example.com', 'HR Assistant');
INSERT INTO `sql_lianxi` (`姓名`, `email`, `job_title`) VALUES ('Tom Martin', 'tom.martin@example.com', 'Software Developer');
INSERT INTO `sql_lianxi` (`姓名`, `email`, `job_title`) VALUES ('Amy White', 'amy.white@example.com', 'Marketing Manager');
INSERT INTO `sql_lianxi` (`dept_name`, `location`) VALUES ('HR', 'New York');
INSERT INTO `sql_lianxi` (`dept_name`, `location`) VALUES ('IT', 'San Francisco');
INSERT INTO `sql_lianxi` (`dept_name`, `location`) VALUES ('Finance', 'Chicago');
INSERT INTO `sql_lianxi` (`dept_name`, `location`) VALUES ('Marketing', 'Los Angeles');
INSERT INTO `sql_lianxi` (`dept_name`, `location`) VALUES ('Operations', 'Houston');
INSERT INTO `sql_lianxi` (`姓名`, `salary`) VALUES ('John Doe', 75000.00);
INSERT INTO `sql_lianxi` (`姓名`, `salary`) VALUES ('Jane Smith', 85000.00);
INSERT INTO `sql_lianxi` (`姓名`, `salary`) VALUES ('David Wilson', 80000.00);
INSERT INTO `sql_lianxi` (`姓名`, `salary`) VALUES ('Tom Martin', 82000.00);
INSERT INTO `sql_lianxi` (`姓名`, `salary`) VALUES ('Amy White', 78000.00);
INSERT INTO `sql_lianxi` (`emp_id`, `first_name`, `last_name`, `email`, `phone_number`, `hire_date`, `job_title`, `salary`, `dept_id`) VALUES (2, 'Jane', 'Smith', 'jane.smith@example.com', '2345678901', '2019-05-20', 'Software Engineer', 85000.00, 2);
INSERT INTO `sql_lianxi` (`emp_id`, `first_name`, `last_name`, `email`, `phone_number`, `hire_date`, `job_title`, `salary`, `dept_id`) VALUES (6, 'Sarah', 'Lee', 'sarah.lee@example.com', '6789012345', '2020-07-01', 'IT Support', 60000.00, 2);
INSERT INTO `sql_lianxi` (`emp_id`, `first_name`, `last_name`, `email`, `phone_number`, `hire_date`, `job_title`, `salary`, `dept_id`) VALUES (9, 'Tom', 'Martin', 'tom.martin@example.com', '9012345678', '2018-06-15', 'Software Developer', 82000.00, 2);
