INSERT INTO `练习` (`student_id`, `name`, `gender`, `birth_date`, `my_class`) VALUES ('2021001', '张三', '男', '2003-05-15', '计算机一班');
INSERT INTO `练习` (`student_id`, `name`, `gender`, `birth_date`, `my_class`) VALUES ('2021002', '李四', '女', '2003-08-22', '计算机一班');
INSERT INTO `练习` (`student_id`, `name`, `gender`, `birth_date`, `my_class`) VALUES ('2021003', '王五', '男', '2002-11-30', '数学一班');
INSERT INTO `练习` (`student_id`, `name`, `gender`, `birth_date`, `my_class`) VALUES ('2021004', '赵六', '女', '2003-02-14', '数学一班');
INSERT INTO `练习` (`student_id`, `name`, `gender`, `birth_date`, `my_class`) VALUES ('2021005', '钱七', '男', '2002-07-08', '物理一班');
INSERT INTO `练习` (`student_id`, `name`, `gender`, `birth_date`, `my_class`) VALUES ('2021006', '孙八', '女', '2003-09-19', '物理一班');
INSERT INTO `练习` (`student_id`, `name`, `gender`, `birth_date`, `my_class`) VALUES ('2021007', '周九', '男', '2002-12-01', '化学一班');
INSERT INTO `练习` (`student_id`, `name`, `gender`, `birth_date`, `my_class`) VALUES ('2021008', '吴十', '女', '2003-03-25', '化学一班');
INSERT INTO `练习` (`student_id`, `name`, `gender`, `birth_date`, `my_class`) VALUES ('2021009', '郑十一', '男', '2002-06-11', '生物一班');
INSERT INTO `练习` (`student_id`, `name`, `gender`, `birth_date`, `my_class`) VALUES ('2021010', '王十二', '女', '2003-10-05', '生物一班');
INSERT INTO `练习` (`course_id`, `course_name`, `teacher_id`, `credits`) VALUES ('C001', '高等数学', 'T001', 4.0);
INSERT INTO `练习` (`course_id`, `course_name`, `teacher_id`, `credits`) VALUES ('C002', '大学物理', 'T002', 3.5);
INSERT INTO `练习` (`course_id`, `course_name`, `teacher_id`, `credits`) VALUES ('C003', '程序设计', 'T003', 4.0);
INSERT INTO `练习` (`course_id`, `course_name`, `teacher_id`, `credits`) VALUES ('C004', '数据结构', 'T004', 3.5);
INSERT INTO `练习` (`course_id`, `course_name`, `teacher_id`, `credits`) VALUES ('C005', '数据库原理', 'T005', 4.0);
INSERT INTO `练习` (`course_id`, `course_name`, `teacher_id`, `credits`) VALUES ('C006', '操作系统', 'T006', 3.5);
INSERT INTO `练习` (`name`, `student_id`, `my_class`) VALUES ('张三', '2021001', '计算机一班');
INSERT INTO `练习` (`name`, `student_id`, `my_class`) VALUES ('李四', '2021002', '计算机一班');
INSERT INTO `练习` (`name`, `student_id`, `my_class`) VALUES ('王五', '2021003', '数学一班');
INSERT INTO `练习` (`name`, `student_id`, `my_class`) VALUES ('赵六', '2021004', '数学一班');
INSERT INTO `练习` (`name`, `student_id`, `my_class`) VALUES ('钱七', '2021005', '物理一班');
INSERT INTO `练习` (`name`, `student_id`, `my_class`) VALUES ('孙八', '2021006', '物理一班');
INSERT INTO `练习` (`name`, `student_id`, `my_class`) VALUES ('周九', '2021007', '化学一班');
INSERT INTO `练习` (`name`, `student_id`, `my_class`) VALUES ('吴十', '2021008', '化学一班');
INSERT INTO `练习` (`name`, `student_id`, `my_class`) VALUES ('郑十一', '2021009', '生物一班');
INSERT INTO `练习` (`name`, `student_id`, `my_class`) VALUES ('王十二', '2021010', '生物一班');
INSERT INTO `练习` (`name`, `title`) VALUES ('张教授', '教授');
INSERT INTO `练习` (`name`, `title`) VALUES ('李副教授', '副教授');
INSERT INTO `练习` (`name`, `title`) VALUES ('王讲师', '讲师');
INSERT INTO `练习` (`name`, `title`) VALUES ('赵助教', '助教');
INSERT INTO `练习` (`name`, `title`) VALUES ('钱教授', '教授');
INSERT INTO `练习` (`name`, `title`) VALUES ('孙副教授', '副教授');
INSERT INTO `练习` (`name`, `title`) VALUES ('周讲师', '讲师');
INSERT INTO `练习` (`name`, `title`) VALUES ('吴助教', '助教');
INSERT INTO `练习` (`name`, `title`) VALUES ('郑教授', '教授');
INSERT INTO `练习` (`name`, `title`) VALUES ('刘副教授', '副教授');
INSERT INTO `练习` (`course_id`, `平均分数`) VALUES ('C001', 81.41667);
INSERT INTO `练习` (`course_id`, `平均分数`) VALUES ('C002', 80.08333);
INSERT INTO `练习` (`course_id`, `平均分数`) VALUES ('C003', 82.90000);
INSERT INTO `练习` (`course_id`, `平均分数`) VALUES ('C004', 82.80000);
INSERT INTO `练习` (`course_id`, `平均分数`) VALUES ('C005', 83.37500);
INSERT INTO `练习` (`course_id`, `平均分数`) VALUES ('C006', 89.12500);
INSERT INTO `练习` (`name`, `平均分数`) VALUES ('张三', 84.66667);
INSERT INTO `练习` (`name`, `平均分数`) VALUES ('李四', 77.83333);
INSERT INTO `练习` (`name`, `平均分数`) VALUES ('王五', 77.00000);
INSERT INTO `练习` (`name`, `平均分数`) VALUES ('赵六', 89.00000);
INSERT INTO `练习` (`name`, `平均分数`) VALUES ('钱七', 77.50000);
INSERT INTO `练习` (`name`, `平均分数`) VALUES ('孙八', 84.16667);
INSERT INTO `练习` (`name`, `平均分数`) VALUES ('周九', 92.33333);
INSERT INTO `练习` (`name`, `平均分数`) VALUES ('吴十', 88.33333);
INSERT INTO `练习` (`name`, `平均分数`) VALUES ('郑十一', 76.00000);
INSERT INTO `练习` (`name`, `平均分数`) VALUES ('王十二', 82.33333);
INSERT INTO `练习` (`student_id`, `course_id`) VALUES ('2021001', 'C001');
INSERT INTO `练习` (`student_id`, `course_id`) VALUES ('2021001', 'C003');
INSERT INTO `练习` (`student_id`, `course_id`) VALUES ('2021002', 'C001');
INSERT INTO `练习` (`student_id`, `course_id`) VALUES ('2021004', 'C002');
INSERT INTO `练习` (`student_id`, `course_id`) VALUES ('2021004', 'C004');
INSERT INTO `练习` (`student_id`, `course_id`) VALUES ('2021004', 'C006');
INSERT INTO `练习` (`student_id`, `course_id`) VALUES ('2021005', 'C003');
INSERT INTO `练习` (`student_id`, `course_id`) VALUES ('2021006', 'C006');
INSERT INTO `练习` (`student_id`, `course_id`) VALUES ('2021007', 'C001');
INSERT INTO `练习` (`student_id`, `course_id`) VALUES ('2021007', 'C003');
INSERT INTO `练习` (`student_id`, `course_id`) VALUES ('2021007', 'C005');
INSERT INTO `练习` (`student_id`, `course_id`) VALUES ('2021008', 'C002');
INSERT INTO `练习` (`student_id`, `course_id`) VALUES ('2021008', 'C004');
INSERT INTO `练习` (`student_id`, `course_id`) VALUES ('2021008', 'C006');
INSERT INTO `练习` (`student_id`, `course_id`) VALUES ('2021009', 'C005');
INSERT INTO `练习` (`student_id`, `course_id`) VALUES ('2021010', 'C004');
INSERT INTO `练习` (`student_id`, `course_id`) VALUES ('2021010', 'C006');
INSERT INTO `练习` (`course_name`, `选课人数`) VALUES ('高等数学', 6);
INSERT INTO `练习` (`course_name`, `选课人数`) VALUES ('大学物理', 6);
INSERT INTO `练习` (`course_name`, `选课人数`) VALUES ('程序设计', 5);
INSERT INTO `练习` (`course_name`, `选课人数`) VALUES ('数据结构', 5);
INSERT INTO `练习` (`course_name`, `选课人数`) VALUES ('数据库原理', 4);
INSERT INTO `练习` (`course_name`, `选课人数`) VALUES ('操作系统', 4);
INSERT INTO `练习` (`name`, `score`) VALUES ('张三', 85.5);
INSERT INTO `练习` (`name`, `score`) VALUES ('李四', 92.0);
INSERT INTO `练习` (`name`, `score`) VALUES ('王五', 76.5);
INSERT INTO `练习` (`name`, `score`) VALUES ('钱七', 61.0);
INSERT INTO `练习` (`name`, `score`) VALUES ('周九', 93.5);
INSERT INTO `练习` (`name`, `score`) VALUES ('郑十一', 80.0);
INSERT INTO `练习` (`name`) VALUES ('王五');
INSERT INTO `练习` (`name`) VALUES ('钱七');
INSERT INTO `练习` (`name`) VALUES ('周九');
INSERT INTO `练习` (`name`) VALUES ('郑十一');
INSERT INTO `练习` (`student_id`, `name`, `gender`, `birth_date`, `my_class`, `score`, `score`) VALUES ('2021001', '张三', '男', '2003-05-15', '计算机一班', 85.5, 78.0);
INSERT INTO `练习` (`student_id`, `name`, `gender`, `birth_date`, `my_class`, `score`, `score`) VALUES ('2021002', '李四', '女', '2003-08-22', '计算机一班', 92.0, 83.5);
INSERT INTO `练习` (`course_id`, `course_name`, `85-100`, `70-84`, `60-69`, `0-59`, `85-100百分比`, `70-84百分比`, `60-69百分比`, `0-59百分比`) VALUES ('C001', '高等数学', 3, 2, 1, 0, 50.00, 33.33, 16.67, 0.00);
INSERT INTO `练习` (`course_id`, `course_name`, `85-100`, `70-84`, `60-69`, `0-59`, `85-100百分比`, `70-84百分比`, `60-69百分比`, `0-59百分比`) VALUES ('C002', '大学物理', 2, 3, 1, 0, 33.33, 50.00, 16.67, 0.00);
INSERT INTO `练习` (`course_id`, `course_name`, `85-100`, `70-84`, `60-69`, `0-59`, `85-100百分比`, `70-84百分比`, `60-69百分比`, `0-59百分比`) VALUES ('C003', '程序设计', 4, 0, 1, 0, 80.00, 0.00, 20.00, 0.00);
INSERT INTO `练习` (`course_id`, `course_name`, `85-100`, `70-84`, `60-69`, `0-59`, `85-100百分比`, `70-84百分比`, `60-69百分比`, `0-59百分比`) VALUES ('C004', '数据结构', 3, 1, 0, 1, 60.00, 20.00, 0.00, 20.00);
INSERT INTO `练习` (`course_id`, `course_name`, `85-100`, `70-84`, `60-69`, `0-59`, `85-100百分比`, `70-84百分比`, `60-69百分比`, `0-59百分比`) VALUES ('C005', '数据库原理', 2, 1, 0, 0, 50.00, 25.00, 0.00, 0.00);
INSERT INTO `练习` (`course_id`, `course_name`, `85-100`, `70-84`, `60-69`, `0-59`, `85-100百分比`, `70-84百分比`, `60-69百分比`, `0-59百分比`) VALUES ('C006', '操作系统', 4, 0, 0, 0, 100.00, 0.00, 0.00, 0.00);
INSERT INTO `练习` (`student_id`, `name`, `score`, `score`) VALUES ('2021001', '张三', 78.0, NULL);
INSERT INTO `练习` (`name`, `average_score`) VALUES ('周九', 92.33333);
INSERT INTO `练习` (`name`, `total_score`) VALUES ('周九', 277.0);
INSERT INTO `练习` (`name`, `total_score`) VALUES ('赵六', 267.0);
INSERT INTO `练习` (`name`, `total_score`) VALUES ('吴十', 265.0);
INSERT INTO `练习` (`name`) VALUES ('赵六');
INSERT INTO `练习` (`name`) VALUES ('周九');
INSERT INTO `练习` (`name`) VALUES ('吴十');
INSERT INTO `练习` (`gender`, `人数`) VALUES ('男', 5);
INSERT INTO `练习` (`gender`, `人数`) VALUES ('女', 5);
INSERT INTO `练习` (`name`) VALUES ('郑十一');
INSERT INTO `练习` (`name`) VALUES ('赵助教');
INSERT INTO `练习` (`student_id`, `name`, `gender`, `birth_date`, `my_class`) VALUES ('2021001', '张三', '男', '2003-05-15', '计算机一班');
INSERT INTO `练习` (`student_id`, `name`, `gender`, `birth_date`, `my_class`) VALUES ('2021002', '李四', '女', '2003-08-22', '计算机一班');
INSERT INTO `练习` (`student_id`, `name`, `gender`, `birth_date`, `my_class`) VALUES ('2021003', '王五', '男', '2002-11-30', '数学一班');
INSERT INTO `练习` (`student_id`, `name`, `gender`, `birth_date`, `my_class`) VALUES ('2021005', '钱七', '男', '2002-07-08', '物理一班');
INSERT INTO `练习` (`student_id`, `name`, `gender`, `birth_date`, `my_class`) VALUES ('2021007', '周九', '男', '2002-12-01', '化学一班');
INSERT INTO `练习` (`student_id`, `name`, `gender`, `birth_date`, `my_class`) VALUES ('2021009', '郑十一', '男', '2002-06-11', '生物一班');
INSERT INTO `练习` (`student_id`, `name`, `gender`, `birth_date`, `my_class`) VALUES ('2021002', '李四', '女', '2003-08-22', '计算机一班');
INSERT INTO `练习` (`student_id`, `name`, `gender`, `birth_date`, `my_class`) VALUES ('2021003', '王五', '男', '2002-11-30', '数学一班');
INSERT INTO `练习` (`student_id`, `name`, `gender`, `birth_date`, `my_class`) VALUES ('2021005', '钱七', '男', '2002-07-08', '物理一班');
INSERT INTO `练习` (`student_id`, `name`, `gender`, `birth_date`, `my_class`) VALUES ('2021007', '周九', '男', '2002-12-01', '化学一班');
INSERT INTO `练习` (`student_id`, `name`, `gender`, `birth_date`, `my_class`) VALUES ('2021009', '郑十一', '男', '2002-06-11', '生物一班');
INSERT INTO `练习` (`student_id`, `name`, `gender`, `birth_date`, `my_class`) VALUES ('2021004', '赵六', '女', '2003-02-14', '数学一班');
INSERT INTO `练习` (`student_id`, `name`, `gender`, `birth_date`, `my_class`) VALUES ('2021006', '孙八', '女', '2003-09-19', '物理一班');
INSERT INTO `练习` (`student_id`, `name`, `gender`, `birth_date`, `my_class`) VALUES ('2021008', '吴十', '女', '2003-03-25', '化学一班');
INSERT INTO `练习` (`student_id`, `name`, `gender`, `birth_date`, `my_class`) VALUES ('2021010', '王十二', '女', '2003-10-05', '生物一班');
INSERT INTO `练习` (`course_name`, `average_score`) VALUES ('操作系统', 89.12500);
INSERT INTO `练习` (`course_name`, `average_score`) VALUES ('数据库原理', 83.37500);
INSERT INTO `练习` (`course_name`, `average_score`) VALUES ('程序设计', 82.90000);
INSERT INTO `练习` (`course_name`, `average_score`) VALUES ('数据结构', 82.80000);
INSERT INTO `练习` (`course_name`, `average_score`) VALUES ('高等数学', 81.41667);
INSERT INTO `练习` (`course_name`, `average_score`) VALUES ('大学物理', 80.08333);
INSERT INTO `练习` (`course_name`, `score`) VALUES ('高等数学', 85.5);
INSERT INTO `练习` (`course_name`, `score`) VALUES ('大学物理', 78.0);
INSERT INTO `练习` (`course_name`, `score`) VALUES ('程序设计', 90.5);
INSERT INTO `练习` (`name`, `course_name`, `score`) VALUES ('张三', '高等数学', 85.5);
INSERT INTO `练习` (`name`, `course_name`, `score`) VALUES ('张三', '大学物理', 78.0);
INSERT INTO `练习` (`name`, `course_name`, `score`) VALUES ('张三', '程序设计', 90.5);
INSERT INTO `练习` (`name`, `course_name`, `score`) VALUES ('李四', '高等数学', 92.0);
INSERT INTO `练习` (`name`, `course_name`, `score`) VALUES ('李四', '大学物理', 83.5);
INSERT INTO `练习` (`name`, `course_name`, `score`) VALUES ('李四', '数据结构', 58.0);
INSERT INTO `练习` (`name`, `course_name`, `score`) VALUES ('王五', '高等数学', 76.5);
INSERT INTO `练习` (`name`, `course_name`, `score`) VALUES ('王五', '程序设计', 85.0);
INSERT INTO `练习` (`name`, `course_name`, `score`) VALUES ('王五', '数据库原理', 69.5);
INSERT INTO `练习` (`name`, `course_name`, `score`) VALUES ('赵六', '大学物理', 88.5);
INSERT INTO `练习` (`name`, `course_name`, `score`) VALUES ('赵六', '数据结构', 92.5);
INSERT INTO `练习` (`name`, `course_name`, `score`) VALUES ('赵六', '操作系统', 86.0);
INSERT INTO `练习` (`name`, `course_name`, `score`) VALUES ('钱七', '高等数学', 61.0);
INSERT INTO `练习` (`name`, `course_name`, `score`) VALUES ('钱七', '程序设计', 87.5);
INSERT INTO `练习` (`name`, `course_name`, `score`) VALUES ('钱七', '数据库原理', 84.0);
INSERT INTO `练习` (`name`, `course_name`, `score`) VALUES ('孙八', '大学物理', 79.5);
INSERT INTO `练习` (`name`, `course_name`, `score`) VALUES ('孙八', '数据结构', 83.0);
INSERT INTO `练习` (`name`, `course_name`, `score`) VALUES ('孙八', '操作系统', 90.0);
INSERT INTO `练习` (`name`, `course_name`, `score`) VALUES ('周九', '高等数学', 93.5);
INSERT INTO `练习` (`name`, `course_name`, `score`) VALUES ('周九', '程序设计', 89.0);
INSERT INTO `练习` (`name`, `course_name`, `score`) VALUES ('周九', '数据库原理', 94.5);
INSERT INTO `练习` (`name`, `course_name`, `score`) VALUES ('吴十', '大学物理', 86.5);
INSERT INTO `练习` (`name`, `course_name`, `score`) VALUES ('吴十', '数据结构', 91.0);
INSERT INTO `练习` (`name`, `course_name`, `score`) VALUES ('吴十', '操作系统', 87.5);
INSERT INTO `练习` (`name`, `course_name`, `score`) VALUES ('郑十一', '高等数学', 80.0);
INSERT INTO `练习` (`name`, `course_name`, `score`) VALUES ('郑十一', '程序设计', 62.5);
INSERT INTO `练习` (`name`, `course_name`, `score`) VALUES ('郑十一', '数据库原理', 85.5);
INSERT INTO `练习` (`name`, `course_name`, `score`) VALUES ('王十二', '大学物理', 64.5);
INSERT INTO `练习` (`name`, `course_name`, `score`) VALUES ('王十二', '数据结构', 89.5);
INSERT INTO `练习` (`name`, `course_name`, `score`) VALUES ('王十二', '操作系统', 93.0);
INSERT INTO `练习` (`name`, `平均分数`) VALUES ('张教授', 81.41667);
INSERT INTO `练习` (`name`, `平均分数`) VALUES ('李副教授', 80.08333);
INSERT INTO `练习` (`name`, `平均分数`) VALUES ('王讲师', 82.90000);
INSERT INTO `练习` (`name`, `平均分数`) VALUES ('赵助教', 82.80000);
INSERT INTO `练习` (`name`, `平均分数`) VALUES ('钱教授', 83.37500);
INSERT INTO `练习` (`name`, `平均分数`) VALUES ('孙副教授', 89.12500);
INSERT INTO `练习` (`name`, `course_name`) VALUES ('张三', '高等数学');
INSERT INTO `练习` (`name`, `course_name`) VALUES ('李四', '大学物理');
INSERT INTO `练习` (`name`, `course_name`) VALUES ('王五', '程序设计');
INSERT INTO `练习` (`name`, `course_name`) VALUES ('赵六', '大学物理');
INSERT INTO `练习` (`name`, `course_name`) VALUES ('赵六', '操作系统');
INSERT INTO `练习` (`name`, `course_name`) VALUES ('钱七', '程序设计');
INSERT INTO `练习` (`name`, `course_name`) VALUES ('钱七', '数据库原理');
INSERT INTO `练习` (`name`, `course_name`) VALUES ('孙八', '数据结构');
INSERT INTO `练习` (`name`, `course_name`) VALUES ('孙八', '操作系统');
INSERT INTO `练习` (`name`, `course_name`) VALUES ('周九', '程序设计');
INSERT INTO `练习` (`name`, `course_name`) VALUES ('吴十', '大学物理');
INSERT INTO `练习` (`name`, `course_name`) VALUES ('吴十', '操作系统');
INSERT INTO `练习` (`name`, `course_name`) VALUES ('郑十一', '高等数学');
INSERT INTO `练习` (`name`, `course_name`) VALUES ('郑十一', '数据库原理');
INSERT INTO `练习` (`name`, `course_name`) VALUES ('王十二', '数据结构');
INSERT INTO `练习` (`my_class`, `平均分数`) VALUES ('计算机一班', 81.25000);
INSERT INTO `练习` (`my_class`, `平均分数`) VALUES ('数学一班', 83.00000);
INSERT INTO `练习` (`my_class`, `平均分数`) VALUES ('物理一班', 80.83333);
INSERT INTO `练习` (`my_class`, `平均分数`) VALUES ('化学一班', 90.33333);
INSERT INTO `练习` (`my_class`, `平均分数`) VALUES ('生物一班', 79.16667);
INSERT INTO `练习` (`name`) VALUES ('李四');
INSERT INTO `练习` (`name`) VALUES ('赵六');
INSERT INTO `练习` (`name`) VALUES ('孙八');
INSERT INTO `练习` (`name`) VALUES ('吴十');
INSERT INTO `练习` (`name`) VALUES ('王十二');
INSERT INTO `练习` (`student_id`, `name`, `平均成绩`) VALUES ('2021002', '李四', 70.75000);
INSERT INTO `练习` (`student_id`, `name`, `平均成绩`) VALUES ('2021003', '王五', 73.00000);
INSERT INTO `练习` (`student_id`, `name`, `平均成绩`) VALUES ('2021005', '钱七', 72.50000);
INSERT INTO `练习` (`student_id`, `name`, `平均成绩`) VALUES ('2021006', '孙八', 81.25000);
INSERT INTO `练习` (`student_id`, `name`, `平均成绩`) VALUES ('2021009', '郑十一', 71.25000);
INSERT INTO `练习` (`name`, `total_score`) VALUES ('周九', 277.0);
INSERT INTO `练习` (`name`, `total_score`) VALUES ('赵六', 267.0);
INSERT INTO `练习` (`name`, `total_score`) VALUES ('吴十', 265.0);
INSERT INTO `练习` (`name`, `total_score`) VALUES ('张三', 254.0);
INSERT INTO `练习` (`name`, `total_score`) VALUES ('孙八', 252.5);
INSERT INTO `练习` (`name`, `total_score`) VALUES ('王十二', 247.0);
INSERT INTO `练习` (`name`, `total_score`) VALUES ('李四', 233.5);
INSERT INTO `练习` (`name`, `total_score`) VALUES ('钱七', 232.5);
INSERT INTO `练习` (`name`, `total_score`) VALUES ('王五', 231.0);
INSERT INTO `练习` (`name`, `total_score`) VALUES ('郑十一', 228.0);
INSERT INTO `练习` (`course_name`) VALUES ('操作系统');
INSERT INTO `练习` (`name`, `平均成绩`, `排名`) VALUES ('周九', 92.33333, 1);
INSERT INTO `练习` (`name`, `平均成绩`, `排名`) VALUES ('赵六', 89.00000, 2);
INSERT INTO `练习` (`name`, `平均成绩`, `排名`) VALUES ('吴十', 88.33333, 3);
INSERT INTO `练习` (`name`, `平均成绩`, `排名`) VALUES ('张三', 84.66667, 4);
INSERT INTO `练习` (`name`, `平均成绩`, `排名`) VALUES ('孙八', 84.16667, 5);
INSERT INTO `练习` (`name`, `平均成绩`, `排名`) VALUES ('王十二', 82.33333, 6);
INSERT INTO `练习` (`name`, `平均成绩`, `排名`) VALUES ('李四', 77.83333, 7);
INSERT INTO `练习` (`name`, `平均成绩`, `排名`) VALUES ('钱七', 77.50000, 8);
INSERT INTO `练习` (`name`, `平均成绩`, `排名`) VALUES ('王五', 77.00000, 9);
INSERT INTO `练习` (`name`, `平均成绩`, `排名`) VALUES ('郑十一', 76.00000, 10);
INSERT INTO `练习` (`course_name`, `name`, `score`) VALUES ('程序设计', '张三', 90.5);
INSERT INTO `练习` (`course_name`, `name`, `score`) VALUES ('大学物理', '赵六', 88.5);
INSERT INTO `练习` (`course_name`, `name`, `score`) VALUES ('数据结构', '赵六', 92.5);
INSERT INTO `练习` (`course_name`, `name`, `score`) VALUES ('高等数学', '周九', 93.5);
INSERT INTO `练习` (`course_name`, `name`, `score`) VALUES ('数据库原理', '周九', 94.5);
INSERT INTO `练习` (`course_name`, `name`, `score`) VALUES ('操作系统', '王十二', 93.0);
INSERT INTO `练习` (`name`) VALUES ('张三');
INSERT INTO `练习` (`name`) VALUES ('李四');
INSERT INTO `练习` (`name`, `course_name`, `score`, `avg_score`) VALUES ('周九', '高等数学', 93.5, 92.33333);
INSERT INTO `练习` (`name`, `course_name`, `score`, `avg_score`) VALUES ('周九', '程序设计', 89.0, 92.33333);
INSERT INTO `练习` (`name`, `course_name`, `score`, `avg_score`) VALUES ('周九', '数据库原理', 94.5, 92.33333);
INSERT INTO `练习` (`name`, `course_name`, `score`, `avg_score`) VALUES ('赵六', '大学物理', 88.5, 89.00000);
INSERT INTO `练习` (`name`, `course_name`, `score`, `avg_score`) VALUES ('赵六', '数据结构', 92.5, 89.00000);
INSERT INTO `练习` (`name`, `course_name`, `score`, `avg_score`) VALUES ('赵六', '操作系统', 86.0, 89.00000);
INSERT INTO `练习` (`name`, `course_name`, `score`, `avg_score`) VALUES ('吴十', '大学物理', 86.5, 88.33333);
INSERT INTO `练习` (`name`, `course_name`, `score`, `avg_score`) VALUES ('吴十', '数据结构', 91.0, 88.33333);
INSERT INTO `练习` (`name`, `course_name`, `score`, `avg_score`) VALUES ('吴十', '操作系统', 87.5, 88.33333);
INSERT INTO `练习` (`name`, `course_name`, `score`, `avg_score`) VALUES ('张三', '高等数学', 85.5, 84.66667);
INSERT INTO `练习` (`name`, `course_name`, `score`, `avg_score`) VALUES ('张三', '大学物理', 78.0, 84.66667);
INSERT INTO `练习` (`name`, `course_name`, `score`, `avg_score`) VALUES ('张三', '程序设计', 90.5, 84.66667);
INSERT INTO `练习` (`name`, `course_name`, `score`, `avg_score`) VALUES ('孙八', '大学物理', 79.5, 84.16667);
INSERT INTO `练习` (`name`, `course_name`, `score`, `avg_score`) VALUES ('孙八', '数据结构', 83.0, 84.16667);
INSERT INTO `练习` (`name`, `course_name`, `score`, `avg_score`) VALUES ('孙八', '操作系统', 90.0, 84.16667);
INSERT INTO `练习` (`name`, `course_name`, `score`, `avg_score`) VALUES ('王十二', '大学物理', 64.5, 82.33333);
INSERT INTO `练习` (`name`, `course_name`, `score`, `avg_score`) VALUES ('王十二', '数据结构', 89.5, 82.33333);
INSERT INTO `练习` (`name`, `course_name`, `score`, `avg_score`) VALUES ('王十二', '操作系统', 93.0, 82.33333);
INSERT INTO `练习` (`name`, `course_name`, `score`, `avg_score`) VALUES ('李四', '高等数学', 92.0, 77.83333);
INSERT INTO `练习` (`name`, `course_name`, `score`, `avg_score`) VALUES ('李四', '大学物理', 83.5, 77.83333);
INSERT INTO `练习` (`name`, `course_name`, `score`, `avg_score`) VALUES ('李四', '数据结构', 58.0, 77.83333);
INSERT INTO `练习` (`name`, `course_name`, `score`, `avg_score`) VALUES ('钱七', '高等数学', 61.0, 77.50000);
INSERT INTO `练习` (`name`, `course_name`, `score`, `avg_score`) VALUES ('钱七', '程序设计', 87.5, 77.50000);
INSERT INTO `练习` (`name`, `course_name`, `score`, `avg_score`) VALUES ('钱七', '数据库原理', 84.0, 77.50000);
INSERT INTO `练习` (`name`, `course_name`, `score`, `avg_score`) VALUES ('王五', '高等数学', 76.5, 77.00000);
INSERT INTO `练习` (`name`, `course_name`, `score`, `avg_score`) VALUES ('王五', '程序设计', 85.0, 77.00000);
INSERT INTO `练习` (`name`, `course_name`, `score`, `avg_score`) VALUES ('王五', '数据库原理', 69.5, 77.00000);
INSERT INTO `练习` (`name`, `course_name`, `score`, `avg_score`) VALUES ('郑十一', '高等数学', 80.0, 76.00000);
INSERT INTO `练习` (`name`, `course_name`, `score`, `avg_score`) VALUES ('郑十一', '程序设计', 62.5, 76.00000);
INSERT INTO `练习` (`name`, `course_name`, `score`, `avg_score`) VALUES ('郑十一', '数据库原理', 85.5, 76.00000);
INSERT INTO `练习` (`name`, `score`) VALUES ('李四', 58.0);
INSERT INTO `练习` (`name`, `score`) VALUES ('周九', 94.5);
INSERT INTO `练习` (`my_class`, `最高分`, `最低分`) VALUES ('计算机一班', 92.0, 58.0);
INSERT INTO `练习` (`my_class`, `最高分`, `最低分`) VALUES ('数学一班', 92.5, 69.5);
INSERT INTO `练习` (`my_class`, `最高分`, `最低分`) VALUES ('物理一班', 90.0, 61.0);
INSERT INTO `练习` (`my_class`, `最高分`, `最低分`) VALUES ('化学一班', 94.5, 86.5);
INSERT INTO `练习` (`my_class`, `最高分`, `最低分`) VALUES ('生物一班', 93.0, 62.5);
INSERT INTO `练习` (`course_name`, `优秀率`) VALUES ('高等数学', 33.3333);
INSERT INTO `练习` (`course_name`, `优秀率`) VALUES ('大学物理', 0.0000);
INSERT INTO `练习` (`course_name`, `优秀率`) VALUES ('程序设计', 20.0000);
INSERT INTO `练习` (`course_name`, `优秀率`) VALUES ('数据结构', 40.0000);
INSERT INTO `练习` (`course_name`, `优秀率`) VALUES ('数据库原理', 25.0000);
INSERT INTO `练习` (`course_name`, `优秀率`) VALUES ('操作系统', 50.0000);
INSERT INTO `练习` (`student_id`, `name`, `gender`, `birth_date`, `my_class`, `p_avg_sc`, `c_avg_sc`) VALUES ('2021001', '张三', '男', '2003-05-15', '计算机一班', 84.66667, 81.250000000);
INSERT INTO `练习` (`student_id`, `name`, `gender`, `birth_date`, `my_class`, `p_avg_sc`, `c_avg_sc`) VALUES ('2021004', '赵六', '女', '2003-02-14', '数学一班', 89.00000, 83.000000000);
INSERT INTO `练习` (`student_id`, `name`, `gender`, `birth_date`, `my_class`, `p_avg_sc`, `c_avg_sc`) VALUES ('2021006', '孙八', '女', '2003-09-19', '物理一班', 84.16667, 80.833330000);
INSERT INTO `练习` (`student_id`, `name`, `gender`, `birth_date`, `my_class`, `p_avg_sc`, `c_avg_sc`) VALUES ('2021007', '周九', '男', '2002-12-01', '化学一班', 92.33333, 90.333330000);
INSERT INTO `练习` (`student_id`, `name`, `gender`, `birth_date`, `my_class`, `p_avg_sc`, `c_avg_sc`) VALUES ('2021010', '王十二', '女', '2003-10-05', '生物一班', 82.33333, 79.166670000);
INSERT INTO `练习` (`name`, `course_name`, `差值`) VALUES ('张三', '高等数学', 4.08333);
INSERT INTO `练习` (`name`, `course_name`, `差值`) VALUES ('李四', '高等数学', 10.58333);
INSERT INTO `练习` (`name`, `course_name`, `差值`) VALUES ('王五', '高等数学', -4.91667);
INSERT INTO `练习` (`name`, `course_name`, `差值`) VALUES ('钱七', '高等数学', -20.41667);
INSERT INTO `练习` (`name`, `course_name`, `差值`) VALUES ('周九', '高等数学', 12.08333);
INSERT INTO `练习` (`name`, `course_name`, `差值`) VALUES ('郑十一', '高等数学', -1.41667);
INSERT INTO `练习` (`name`, `course_name`, `差值`) VALUES ('张三', '大学物理', -2.08333);
INSERT INTO `练习` (`name`, `course_name`, `差值`) VALUES ('李四', '大学物理', 3.41667);
INSERT INTO `练习` (`name`, `course_name`, `差值`) VALUES ('赵六', '大学物理', 8.41667);
INSERT INTO `练习` (`name`, `course_name`, `差值`) VALUES ('孙八', '大学物理', -0.58333);
INSERT INTO `练习` (`name`, `course_name`, `差值`) VALUES ('吴十', '大学物理', 6.41667);
INSERT INTO `练习` (`name`, `course_name`, `差值`) VALUES ('王十二', '大学物理', -15.58333);
INSERT INTO `练习` (`name`, `course_name`, `差值`) VALUES ('张三', '程序设计', 7.60000);
INSERT INTO `练习` (`name`, `course_name`, `差值`) VALUES ('王五', '程序设计', 2.10000);
INSERT INTO `练习` (`name`, `course_name`, `差值`) VALUES ('钱七', '程序设计', 4.60000);
INSERT INTO `练习` (`name`, `course_name`, `差值`) VALUES ('周九', '程序设计', 6.10000);
INSERT INTO `练习` (`name`, `course_name`, `差值`) VALUES ('郑十一', '程序设计', -20.40000);
INSERT INTO `练习` (`name`, `course_name`, `差值`) VALUES ('李四', '数据结构', -24.80000);
INSERT INTO `练习` (`name`, `course_name`, `差值`) VALUES ('赵六', '数据结构', 9.70000);
INSERT INTO `练习` (`name`, `course_name`, `差值`) VALUES ('孙八', '数据结构', 0.20000);
INSERT INTO `练习` (`name`, `course_name`, `差值`) VALUES ('吴十', '数据结构', 8.20000);
INSERT INTO `练习` (`name`, `course_name`, `差值`) VALUES ('王十二', '数据结构', 6.70000);
INSERT INTO `练习` (`name`, `course_name`, `差值`) VALUES ('王五', '数据库原理', -13.87500);
INSERT INTO `练习` (`name`, `course_name`, `差值`) VALUES ('钱七', '数据库原理', 0.62500);
INSERT INTO `练习` (`name`, `course_name`, `差值`) VALUES ('周九', '数据库原理', 11.12500);
INSERT INTO `练习` (`name`, `course_name`, `差值`) VALUES ('郑十一', '数据库原理', 2.12500);
INSERT INTO `练习` (`name`, `course_name`, `差值`) VALUES ('赵六', '操作系统', -3.12500);
INSERT INTO `练习` (`name`, `course_name`, `差值`) VALUES ('孙八', '操作系统', 0.87500);
INSERT INTO `练习` (`name`, `course_name`, `差值`) VALUES ('吴十', '操作系统', -1.62500);
INSERT INTO `练习` (`name`, `course_name`, `差值`) VALUES ('王十二', '操作系统', 3.87500);
